version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
